# main configuration for running experiment
[main]
# choose if use tcp_probe
enable_tcp_probe = false
# choose 'mahimahi' or 'tc' for delay emulator
delay_emulator = 'mahimahi'
[type]
#choose the tpe of experiment
#uni or counter
type="counter"

[unisetting]
#if you choose to run the uniformity experiment
delay_list=[ ["90ms"],["140ms"], ]
prebdw_list=[[ 6, 1, 100000, 1],]
postbdw_list=[[ 24, 1, 100000, 1], [ 48, 2, 100000, 1 ] ,] 
[countersetting]
#if you choose to run the counter experiment
delay_list = [ ["90ms","25ms" ],["140ms" , "70ms"], ]
bdw_list=[ [ 12, 1, 200000, 1],[ 48, 2, 200000, 1] ]
[generalsetting]
packet_buffer_list = ["20p","60p","100p"]
# how many iterations need to run for one set of parameters
iteration = 50
# how long experiment lasts
exp_duration =200
[ccp_algs]
TcpBbr ="bbr"
TcpLinuxReno="reno"
